const {Builder, By, Key, until} = require('selenium-webdriver');

const toolbox_screenshot = "iVBORw0KGgoAAAANSUhEUgAAAMoAAAH+CAYAAADd+ZGnAAABJmlDQ1BTa2lhAAAokX2Ru0oDURCGP4ONoiCoqGCxnTZeNlkSC4NE0WibKCSx2mw2QUzisllR8BV8CDsLH8HGUhREEKx8CLGw9t8NcgISZ5jzf2fOfQ6k5pGlpqDTjcJScduqVGsWA+Z6vYDhNgLf73ELbyv/zBtmYw2/50k/FVGow7VlQzzT6vNlzPU+X8ccHpZ2xDfi5dYA1wf4Igoi8WM83wvCmD/Em532uWfuzYTfPSpLK4pFipzJW7TxWaPMKSe4IpsCGfmewiaHk7S7UkeaU35DI2mycluUY109J9EMBVPPqzxsLanazyZXe4G7OZjdNznrSf0HuF8I3NBNUqPxJzWb8HULk1WYfoXx498imrXmL4a81frzVosDunisitK6s032B6dpSECAM/lMAAAIv0lEQVR4nO3aXciedR3A8d8zJ4JFgkxKXZ1IJNqkxE56YZghOqEXh7CD0BCliJERisUIN2yQUkRgtOUqrRMjBBFMGenyJKjEbI8rITqJ5QsuwZNimFsHe2k6H/cVzSl8PvDAfV3/67mvPw98n+v63/e1sHHjxv0DvKplx3sC8Haw/NCLtWvXHs95wFuaKwoEQoFAKK/BvoU9c88NF8yqVauW/Lli/X3z3Os8z95d2+ayVVvnz0dsf3zVV2fHUz53OV6E8hrsX/bkPPPAtfOLxcVZXFycR+66bt436w9vP7rj1nn/6zzH3l3b5oJ1319ym+NDKK/RWd+6fM5ZYuzEFZfOFWsWXtf7n3TuNfPIXdctuc3xsfzYh3DICS+eN5/6zKsf8+E1a96cyfCmckX5P3j5WubI9UYZX8q//3n/fGXVea+4Ftq7a9tL1kqb7332qP1XrL9vnt6z9HuwNKG8wfYt7Jl7r79kdn3i/llcXJw/Pb5jrr3k9rnhYAzHGl/K8/Pg/HTL/tm4uHMe3XHrnP7wN+Zrtz02MwdiuHzdiy9ZO9214ZOz+d5n56Rzr5lHd9w6F87CvOPsM+e0d585H5hls27zQ/PL2y6bU9+Uv8rbn1DeYC88fs/c/sC187lPnzYzM8v2r5jLbrx5zpofzM5H9x9zfCmnzEXz5Q1r5tQ5sBa68TsXz7NbfzePL+yZ++/YMh/d/L+100nnXjM/vu6d89j2389zB4//7o5b5l1br5zV5/xkztn+x9lw8Pw0QnmD7dn9xFH7lh38L/633XuOOV6tWHn2zMzsW/bk/OOB/xw1fuZ7Pzb/enj3PH1w+1Bcz8+D89s/9PNwgFDeYCtWnj1/n9te8epw1soVxxyv9ux+Yk5evXLO2HfGnHnJ8sNXjyOdvHrlvOfg6727ts2Gv37+8G3ZXa9y9eJoQnmdnp+/zDNHfBF44gc/OzdfctL8/KofHV5zPP2rn81vVm+ei89fOOb4Uu/7/Dw4zzx14PULe+6fW67fPmuvXjMr9q+YS7/wpXni4a/PDw8u4F88Yefcc/2vZ+3VB27V9u7aNl/cccHcsf5Dhz9u3nzVeWJ5DRYOPWbvocju0IL8mw/sPbxv3eaHDt/3v3z87NXfnq1HLJxfbfzILxhPmYvm5u3fmwtPX1hy/yEv/2Jyw507Z935L/29DXfunCs+sjhbzrlytsyLR82bpQkFArdeEAgFAqFAcPhZr7vvvvt4zgPe0pbPzNx0003Hex7wlrVp0ya3XlAIBQKhQCAUCIQCgVAgEAoEQoFAKBAIBQKhQCAUCIQCgVAgEAoEQoFAKBAIBQKhQCAUCIQCgVAgEAoEQoFAKBAIBQKhQCAUCIQCgVAgEAoEQoFAKBAIBQKhQCAUCIQCgVAgEAoEQoFAKBAIBQKhQCAUCIQCgVAgEAoEQoFAKBAIBQKhQCAUCIQCgVAgEAoEQoFAKBAIBQKhQCAUCIQCgVAgEAoEQoFAKBAIBQKhQCAUCIQCgVAgEAoEQoFAKBAIBQKhQCAUCIQCgVAgEAoEQoFAKBAIBQKhQCAUCIQCgVAgEAoEQoFAKBAIBQKhQCAUCIQCgVAgEAoEQoFAKBAIBQKhQCAUCIQCgVAgEAoEQoFAKBAIBQKhQCAUCIQCgVAgEAoEQoFAKBAIBQKhQCAUCIQCgVAgEAoEQoFAKBAIBQKhQCAUCIQCgVAgEAoEQoFAKBAIBQKhQCAUCIQCgVAgEAoEQoFAKBAIBQKhQCAUCIQCgVAgEAoEQoFAKBAIBQKhQCAUCIQCgVAgEAoEQoFAKBAIBQKhQCAUCIQCgVAgEAoEQoFAKBAIBQKhQCAUCIQCgVAgEAoEQoFAKBAIBQKhQCAUCIQCgVAgEAoEQoFAKBAIBQKhQCAUCIQCgVAgEAoEQoFAKBAIBQKhQCAUCIQCgVAgEAoEQoFAKBAIBQKhQCAUCIQCgVAgEAoEQoFAKBAIBQKhQCAUCIQCgVAgEAoEQoFAKBAIBQKhQCAUCIQCgVAgEAoEQoFAKBAIBQKhQCAUCIQCgVAgEAoEQoFAKBAIBQKhQCAUCIQCgVAgEAoEQoFAKBAIBQKhQCAUCIQCgVAgEAoEQoFAKBAIBQKhQCAUCIQCgVAgEAoEQoFAKBAIBQKhQCAUCIQCgVAgEAoEQoFAKBAIBQKhQCAUCIQCgVAgEAoEQoFAKBAIBQKhQCAUCIQCgVAgEAoEQoFAKBAIBQKhQCAUCIQCgVAgEAoEQoFAKBAIBQKhQCAUCIQCgVAgEAoEQoFAKBAIBQKhQCAUCIQCgVAgEAoEQoFAKBAIBQKhQCAUCIQCgVAgEAoEQoFAKBAIBQKhQCAUCIQCgVAgEAoEQoFAKBAIBQKhQCAUCIQCgVAgEAoEQoFAKBAIBQKhQCAUCIQCgVAgEAoEQoFAKBAIBQKhQCAUCIQCgVAgEAoEQoFAKBAIBQKhQCAUCIQCgVAgEAoEQoFAKBAIBQKhQCAUCIQCgVAgEAoEQoFAKBAIBQKhQCAUCIQCgVAgEAoEQoFAKBAIBQKhQCAUCIQCgVAgEAoEQoFAKBAIBQKhQCAUCIQCgVAgEAoEQoFAKBAIBQKhQCAUCIQCgVAgEAoEQoFAKBAIBQKhQCAUCIQCgVAgEAoEQoFAKBAIBQKhQCAUCIQCgVAgEAoEQoFAKBAIBQKhQCAUCIQCgVAgEAoEQoFAKBAIBQKhQCAUCIQCgVAgEAoEQoFAKBAIBQKhQCAUCIQCgVAgEAoEQoFAKBAIBQKhQCAUCIQCgVAgEAoEQoFAKBAIBQKhQCAUCIQCgVAgEAoEQoFAKBAIBQKhQCAUCIQCgVAgEAoEQoFAKBAIBQKhQCAUCIQCgVAgEAoEQoFAKBAIBQKhQCAUCIQCgVAgEAoEQoFAKBAIBQKhQCAUCIQCgVAgEAoEQoFAKBAIBQKhQCAUCIQCgVAgEAoEQoFAKBAIBQKhQCAUCIQCgVAgEAoEy2dmNm3adLznAW9p/wXewXoSWiSYKgAAAABJRU5ErkJggg=="
async function check_load_toolbar()
{
    //console.log('asdasdasd')
    let driver = await new Builder().forBrowser('chrome').build();
    try{
        let toolbox = driver.get('http://127.0.0.1:5500/ArchitectEditor/Testing/toolbox/toolbox.html');

        await driver.manage().window().setRect( { width: 1024, height: 768 } );
        //await driver.sleep( 2000 )
        //driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
        toolbox = await driver.findElement( By.id( 'toolbox' ));
        await toolbox.takeScreenshot( true ).then( ss => {
            if( ss !== toolbox_screenshot ) {
                require('fs').writeFileSync( 'tbtest.png', ss, 'base64');
                throw Error('not equal');
               
            }
        })


    }catch( exc )
    {
        console.log( exc.message + exc.stack );
    } finally{
        driver.close();
    }
}

module.exports = { check_load_toolbar }

check_load_toolbar();